const InterviewSession = require("../models/InterviewSession");
const Resume = require("../models/Resume");

const axios = require("axios");
const path = require("path");


// =====================================
// GENERATE UNIQUE INTERVIEW
// =====================================

const generateInterview = async (req, res) => {

  try {

    const {
      resumeId,
      jobTitle,
      difficulty,
      mode,
      jdContent,
      questionCount
    } = req.body;

    // Validate and bound questionCount (prevent DOS)
    const validatedQuestionCount = Math.max(1, Math.min(50, parseInt(questionCount, 10) || 5));

    // Map user difficulty levels to NLP service levels
    const difficultyMap = {
      'Fresher': 'easy',
      'Junior': 'medium',
      'Mid': 'hard',
      'Senior': 'hard'
    };

    const nlpDifficulty = difficultyMap[difficulty] || 'medium';

    // Find Resume
    const resume = await Resume.findById(
      resumeId
    );

    if (!resume) {

      return res.status(404).json({
        message: "Resume not found"
      });
    }

    // Get Previous Interview Sessions
    const previousSessions =
      await InterviewSession.find({
        user: req.user._id
      });

    // Collect Previously Asked Questions
    let previousQuestions = [];

    previousSessions.forEach((session) => {

      // Previous generated questions
      if (session.questions) {

        previousQuestions.push(
          ...session.questions
        );
      }

      // Previous answered questions
      if (session.answers) {

        session.answers.forEach((answer) => {

          previousQuestions.push(
            answer.question
          );
        });
      }
    });

    // Remove duplicates
    previousQuestions = [
      ...new Set(previousQuestions)
    ];

     // =====================================
    // VALIDATE FILE PATH (ANTI-TRAVERSAL)
    // =====================================

    const UPLOADS_DIR = path.resolve(__dirname, "../../uploads/resumes");

    const validateFilePath = (filePath) => {
      const safePath = path.resolve(UPLOADS_DIR, path.basename(filePath));
      if (!safePath.startsWith(UPLOADS_DIR)) {
        throw new Error("Invalid file path detected");
      }
      return safePath;
    };

    let absoluteResumePath;
    try {
      absoluteResumePath = validateFilePath(resume.filePath);
    } catch (error) {
      return res.status(400).json({
        message: "Invalid resume file path"
      });
    }

    // ===== SECURITY: Sanitize JD content =====
    let sanitizedJD = null;
    if (jdContent) {
      sanitizedJD = jdContent
        .replace(/[${}`\\]/g, "")
        .substring(0, 5000);
    }

    const nlpPayload = {
      file_path: absoluteResumePath,
      difficulty: nlpDifficulty,
      mode,
      previous_questions: previousQuestions
    };

    // Add JD content if provided
    if (sanitizedJD) {
      nlpPayload.jd_content = sanitizedJD;
    }

    const response = await axios.post(
      `${process.env.NLP_SERVICE_URL}/generate-questions`,
      nlpPayload,
      { timeout: 60000 }
    );

    const generatedData = response.data;

    // Validate that skills were extracted
    if (!generatedData.skills || Object.keys(generatedData.skills).length === 0) {
      return res.status(400).json({
        message: "Could not extract skills from resume. Please check your resume format."
      });
    }

    // Check if we have questions (technical or project)
    const hasQuestions = (generatedData.questions && Object.keys(generatedData.questions).length > 0);
    const hasProjectQuestions = (generatedData.project_questions && Object.keys(generatedData.project_questions).length > 0);

    if (!hasQuestions && !hasProjectQuestions) {
      if (process.env.NODE_ENV !== "production") {
        console.log("No questions generated by NLP");
      }
      return res.status(400).json({
        message: "Could not generate questions. Please check your resume content."
      });
    }

    // =====================================
    // FLATTEN QUESTIONS WITH SKILL MAPPING
    // =====================================

    let allQuestions = [];

    // Technical Questions
    Object.entries(
      generatedData.questions
    ).forEach(([skill, questionsArray]) => {

      questionsArray.forEach((q) => {
        allQuestions.push({
          text: q,
          skill: skill,
          type: 'technical'
        });
      });
    });

    // Project Questions
    Object.entries(
      generatedData.project_questions
    ).forEach(([skill, questionsArray]) => {

      questionsArray.forEach((q) => {
        allQuestions.push({
          text: q,
          skill: skill,
          type: 'project'
        });
      });
    });

    // Limit questions to requested count
    const questionLimit = parseInt(questionCount) || 10;
    allQuestions = allQuestions.slice(0, questionLimit);

    const session =
      await InterviewSession.create({

        user: req.user._id,

        jobTitle: jobTitle || 'Technical Interview',

        jdContent: jdContent || null,

        skills:
          generatedData.skills,

        questions:
          allQuestions,

        totalScore: 0,

        answers: []
      });

    // =====================================
    // SUCCESS RESPONSE
    // =====================================

    res.status(200).json({

      message:
        "Unique interview generated successfully",

      difficulty,

      mode,

      skills:
        generatedData.skills,

      questions:
        session.questions,

      project_questions:
        generatedData.project_questions,

      session
    });

  } catch (error) {

    console.error("Interview Generation Error:", error.message);
    console.error("Stack:", error.stack);
    
    res.status(500).json({
      message: "Server Error"
    });


    res.status(500).json({

      message: "Server Error"
    });
  }
};


// =====================================
// COMPREHENSIVE ANSWER EVALUATION
// =====================================

const evaluateAnswer = async (question, answer) => {
  let score = 0;
  const feedback = { strengths: "", weaknesses: "", gaps: "" };
  const lowerAnswer = answer.toLowerCase();

  // Length-based scoring
  if (answer.length > 20) score += 2;
  if (answer.length > 100) score += 2;

  // Specific technical keywords
  const technicalKeywords = {
    "algorithm": 2,
    "database": 2,
    "api": 2,
    "cache": 1,
    "optimize": 2,
    "scalability": 2,
    "design pattern": 2,
    "architecture": 2,
    "microservices": 2,
    "container": 1,
  };

  let keywordCount = 0;
  for (const [keyword, points] of Object.entries(technicalKeywords)) {
    if (lowerAnswer.includes(keyword)) {
      score += points;
      keywordCount++;
    }
  }

  // Analyze answer quality
  const answerLength = answer.length;
  const sentenceCount = answer.split(/[.!?]/).length;

  if (answerLength < 30) {
    feedback.weaknesses = "Answer is too brief. Provide more detailed explanation with examples.";
  } else if (sentenceCount < 2) {
    feedback.weaknesses = "Answer lacks structure. Use multiple sentences to explain different aspects.";
  } else if (keywordCount >= 3) {
    feedback.strengths = "Good use of technical terminology. Answer demonstrates strong conceptual knowledge.";
  } else if (keywordCount > 0) {
    feedback.strengths = "Answer includes relevant technical concepts.";
  }

  // Detect gaps
  if (lowerAnswer.length < 50) {
    feedback.gaps = "Consider adding implementation details, trade-offs, or examples.";
  } else if (!lowerAnswer.includes("example") && !lowerAnswer.includes("e.g") && answerLength < 150) {
    feedback.gaps = "Add concrete examples or use cases to strengthen the answer.";
  }

  // Cap score at 10
  score = Math.min(10, Math.max(0, score));

  try {
    // Call NLP service for deeper analysis if available
    const nlpResponse = await axios.post(
      `${process.env.NLP_SERVICE_URL}/evaluate-answer`,
      { question, answer },
      { timeout: 5000 }
    ).catch(() => null);

    if (nlpResponse?.data) {
      const nlpData = nlpResponse.data;
      if (nlpData.score) score = Math.min(10, nlpData.score);
      if (nlpData.strengths) feedback.strengths = nlpData.strengths;
      if (nlpData.weaknesses) feedback.weaknesses = nlpData.weaknesses;
      if (nlpData.gaps) feedback.gaps = nlpData.gaps;
    }
  } catch (e) {
    if (process.env.NODE_ENV !== "production") {
      console.log("NLP service not available, using basic evaluation");
    }
  }

  return { score, feedback };
};


// =====================================
// SUBMIT ANSWER
// =====================================

const submitAnswer = async (req, res) => {

  try {

    const { sessionId } = req.params;

    const {
      question,
      answer
    } = req.body;

    // Find Interview Session
    const session =
      await InterviewSession.findById(
        sessionId
      );

    if (!session) {

      return res.status(404).json({

        message:
          "Interview session not found"
      });
    }

    // Evaluate Answer (now async with feedback)
    const { score, feedback } =
      await evaluateAnswer(question, answer);

    // Store Answer with feedback
    session.answers.push({

      question,

      answer,

      score,

      feedback
    });

    // Update Total Score
    session.totalScore += score;

    await session.save();

    // Success Response
    res.status(200).json({

      message:
        "Answer submitted successfully",

      score,

      feedback,

      totalScore:
        session.totalScore,

      session
    });

  } catch (error) {

    if (process.env.NODE_ENV !== "production") {
      console.error("Submit Answer Error:", error);
    }

    res.status(500).json({

      message: "Server Error"
    });
  }
};


// =====================================
// GET USER SESSIONS
// =====================================

const getUserSessions = async (req, res) => {
  try {
    const sessions = await InterviewSession.find({ user: req.user._id }).sort({ createdAt: -1 });
    res.json({ sessions });
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};


// =====================================
// GET SINGLE SESSION DETAILS
// =====================================

const getSessionDetails = async (req, res) => {
  try {
    const { sessionId } = req.params;
    const session = await InterviewSession.findOne({
      _id: sessionId,
      user: req.user._id
    });

    if (!session) {
      return res.status(404).json({ message: 'Session not found' });
    }

    res.json({ session });
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};


module.exports = {

  generateInterview,

  submitAnswer,

  getUserSessions,

  getSessionDetails
};